language: python

python:
  - "2.7"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  - pushd deploy
  - ./install_taxbrain_server.sh
  - popd
  - source activate aei_dropq
  - echo installing toolz
  - conda install toolz
  - echo is toolz installed
  - python -c "import toolz; print(toolz.__version__)"


addons:
    postgresql: "9.4"

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - py.test webapp/apps/
