name: aei_dropq
dependencies:
- python=2.7.12
- pandas>=0.20.1
- flask
- greenlet
- xlrd
- redis
- sphinx
- pip:
  - fabric
  - boto
  - celery
  - eventlet==0.20.0
  - retrying
  - plotly
  - sphinx-rtd-theme
  - sphinx-autobuild

channels:
  - ospc
  - defaults
